data_dir: /grogu/user/pmorgado/projects/avl-base/experiments/action-recg/
visualize: False
resume: True
world_size: 1
rank: 0
ngpu: 4
workers: 32
multiprocessing_distributed: True
distributed: True
dist_backend: 'nccl'
dist_url: 'tcp://224.66.41.62:23456'
node: 'localhost'
port: 21995
seed: 0
gpu: ''
slurm: True
slurm_partition: abhinav,all
slurm_timeout: 360
print_freq: ${logging.print_freq}
evaluate: False
nodelist: ""
exclude_nodes: ""
